# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == 'zeros':
        return np.zeros(shape)
    if mode == 'ones':
        return np.ones(shape)
    if mode == 'full':
        return np.full(shape, value)
    if mode == 'identity':
        return np.eye(shape)


: 

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [ ]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [ ]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr


TestCase

In [ ]:
import numpy as np

branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9],
            [10, 11, 12]]

def secure_reshape_and_stack(data1, data2, new_shape):
    arr1 = np.array(data1)
    arr2 = np.array(data2)
    reshaped_arr1 = arr1.reshape(new_shape)
    return np.vstack((reshaped_arr1, arr2))

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


: 

In [ ]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])